### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [sweirich/replib#30]
Hi,

I’m wondering whether to build a project of mine on top of unbound, but especially with academic software, the current maintenance status is unclear. The last upload was a year ago, which is already a lot on hackage.

If unbound were added to stackage, this would give me greater confidence that it is a maintained bit software, as at least build failures and test suite failures will be detected in a timely manner by the stackage guys. So in a way, it is free QA for your!

It is easy to join stackage and does not require you to use stackage or the stack tool: http://www.stackage.org/authors

Greetings,
Joachim

**Comment by sweirich** [comment]
This is super old, but sometime when you get a chance, can you help me do this?

**Comment by nomeata** [comment]
I’ll take care of it, by creating  https://github.com/fpco/stackage/pull/1794.

**Comment by sweirich** [comment]
Thanks!  Do I need to add anything to RepLib/Unbound?  Let me know.

**Comment by nomeata** [comment]
> Do I need to add anything to RepLib/Unbound? Let me know.

I think uploading the current state of the repository (for GHC 8 compat) ought to be enough for now.

**Comment by sweirich** [comment]
Ok. I’ve uploaded the current state of RepLib/Unbound to hackage today.

**Comment by nomeata** [comment]
It seems that some `Example.*` files were missing from the distribution, causing the test suite to fail: https://github.com/fpco/stackage/pull/1794#issuecomment-241256603

**Comment by sweirich** [comment]
How do I get cabal to include those files in the distribution?  They are in the github repo.

**Comment by nomeata** [comment]
The problem was the path name, which was lower case, and thus did not allow ghc to find the source. Fixed in #39.

**Comment by sweirich** [comment]
Thanks!

I now get this error when I try to run cabal test. Can you help?

Stephanies-MacBook-Pro:Unbound sweirich$ cabal test
Re-configuring with test suites enabled. If this fails, please run configure
manually.
Resolving dependencies...
Configuring unbound-0.5.0...
Preprocessing library unbound-0.5.0...

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead

on the commandline: warning:
    -this-package-key is deprecated: Use -this-unit-id instead
In-place registering unbound-0.5.0...
cabal: '/Users/sweirich/local/bin/ghc-pkg' exited with an error:
unbound-0.5.0: installed package info from too old version of Cabal (key field
does not match id field)

**Comment by sweirich** [comment]
Stephanies-MacBook-Pro:Unbound sweirich$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library

**Comment by nomeata** [comment]
> I now get this error when I try to run cabal test. Can you help?

This looks like a problem with your local installation.  `cabal-1.22` does not support GHC-8.0. Here is what [Edward Yang](https://groups.google.com/d/msg/haskell-cafe/WQPmXkauGmE/lgk91YMUBAAJ) writes about the issue:

> Yes, you need to upgrade your cabal-install.
> 
> If you still have an old version of GHC around, you can upgrade using:
> ```
>     cabal update
>     cabal install -w /path/to/old/ghc cabal-install
>```

**Comment by sweirich** [comment]
Ok.  I had updated cabal, but not the one in my path.  Now resolved locally and the version of unbound on hackage should have working tests.
