### ISSUE TITLE
New hackage release

### ISSUE THREAD

**Issue by nomeata** [sweirich/replib#31]
Hi,

I just stumbled over unbound on hackage not being compatible with 7.10, but the version in the git repo has the required fixed. Would you consider an upload to hackage?

Thanks,
Joachim

**Comment by sweirich** [comment]
I just uploaded the current version.   I got this message from hackage:

**Comment by nomeata** [comment]
Thanks!

That message is new to me, but it seems that hackage is encouraging to re-use existing module name prefixes (`Data.`, `Language.` etc.). I would not worry.
