### ISSUE TITLE
Failed to Build with GHC 8.0.1

### ISSUE THREAD

**Issue by heades** [sweirich/replib#34]
Hi!

Replib and Unbound fail to build with latest version of Haskell platform (8.0.1).

Cabal reports several conflicts.  For example:

✗ cabal install replib
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: RepLib-0.5.3.5 (user goal)
trying: base-4.9.0.0/installed-4.9... (dependency of RepLib-0.5.3.5)
next goal: template-haskell (dependency of RepLib-0.5.3.5)
rejecting: template-haskell-2.11.0.0/installed-2.1...,
template-haskell-2.11.0.0 (conflict: RepLib => template-haskell>=2.4 && <2.11)
rejecting: template-haskell-2.10.0.0 (conflict:
base==4.9.0.0/installed-4.9..., template-haskell => base==4.8.*)
rejecting: template-haskell-2.9.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.7.*)
rejecting: template-haskell-2.8.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.6.*)
rejecting: template-haskell-2.7.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.5.*)
rejecting: template-haskell-2.6.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.4.*)
rejecting: template-haskell-2.5.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.3.*)
rejecting: template-haskell-2.4.0.1 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.2.*)
rejecting: template-haskell-2.4.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base>=3 && <4.3)
rejecting: template-haskell-2.3.0.1, template-haskell-2.3.0.0,
template-haskell-2.2.0.0 (conflict: RepLib => template-haskell>=2.4 && <2.11)
Dependency tree exhaustively searched.

I get the same conflicts using this repo.

Are there plans to fix this?

Thanks,
Harley

**Comment by sweirich** [comment]
Hi Harley, 

I'm at a workshop today and tomorrow but I can look at this later this week.  Or if you figure out the issue before that, pull requests welcome!

**Comment by sweirich** [comment]
Ok, I just pushed some changes.  It may work... let me know.

**Comment by heades** [comment]
Hi, Stephanie.

Prefect, it built and installed just fine.

Thanks for working on this so fast.

Best,
Harley

**Comment by sweirich** [comment]
You're welcome.   If you happen to have a good benchmark for Unbound let me know. I've always wanted to add some performance tests to the project.

**Comment by heades** [comment]
I will keep that in mind.  I am sure here by the end of summer we may have something.
