### ISSUE TITLE
`fresh` method misses `Rep a` constraint

### ISSUE THREAD

**Issue by m0rphism** [sweirich/replib#36]
**edit:** Seems this issue occurs only in the hackage version and is already fixed upstream thanks to the `AName` class.

**edit2:** Ok, it is fixed in `Unbound.Name`, but not in `Unbound.LocallyNameless.Name`. Looking at the recent commits, I assume the current commit represents an intermediate state towards a version, where the issue is already fixed, so I'm closing this.

I'm trying to integrate the `unbound` library into a toy compiler with an already existing monad for generating fresh variable names. Hence, I want to make that monad an instance of the `Fresh` type class. Because the `Name` type is abstract, I have to make use of the `makeName` function, which has a `Rep a` constraint. Unfortunately, it seems to me that this constraint can not be satisfied, because the `fresh` method has no `Rep a` constraint. The implementation for `FreshMT` from `unbound` works, because it uses the hidden constructors from `Name`.

If this is by construction to prevent instances for other `FreshMT`-like transformers, it could be considered adding a note to the classes haddock, but I'm not sure this would be a sensible restriction, as it would force larger parts of the client code to work with the `Name` representation, because there seems to be no possibility to conveniently access the `Integer` state inside of `FreshMT` directly.

For completeness, here is my attempt to write a `Fresh` instance:

    instance Monad m => Fresh (MyFreshT m) where
      fresh name = do
        n :: Integer <- myfresh
        pure $ makeName (name2String name) n

which leads to the following error:

    Could not deduce (Rep a) arising from a use of ‘makeName’
    Possible fix:
      add (Rep a) to the context of
        the type signature for:
          fresh :: Name a -> FreshT m (Name a)

**Comment by sweirich** [comment]
Yes, there is code there towards resolving that problem (among many others) but it is not likely to be completed soon.  If you send me a PR that fixes just this issue, I'll incorporate it and then it will be available on the next hackage version.
