### ISSUE TITLE
Show for bound needs space after the bound variables

### ISSUE THREAD

**Issue by kyagrd** [sweirich/replib#40]
Using unbound version 0.5.1 from Hackage, when you print some structures created by bind like this:
```
print $ bind (s2n "a") (bind (s2n "b") (bind (s2n "x") Null))
```
It prints out like this:
```
bind a(bind b(bind xNull))
```
What we want is `x` and `Null` be delimited not `xNull` concatenated as if it were a single identifier. 
I think the easiest fix is to put in a space as a delimiter after printing the bound variable.

**Comment by kyagrd** [comment]
I think adding `showString " "` in the Show instance for printing bind structures will do.
That is, changing line 92 in `Unbound/LocallyNameless/Types.hs` like this.
```
(showString "bind " . showsPrec 11 a . showString " " . showsPrec 11 b)
```

**Comment by sweirich** [comment]
Thanks Ki Yung!  Please send a pull request and I'll merge.

**Comment by kyagrd** [comment]
Here's the pull request 
https://github.com/sweirich/replib/pull/41
