### ISSUE TITLE
upload RepLib that builds with newer template-haskell to hackage?

### ISSUE THREAD

**Issue by chessai** [sweirich/replib#45]
Current RepLib on hackage builds with template-haskell < 2.12, though on `master` RepLib builds with template-haskell 2.12. Would it be possible to upload this to hackage?

Thanks!

**Comment by chessai** [comment]
PR #46 makes RepLib build with GHC 8.4.3 and 8.6.1, and template-haskell 2.13 and 2.14

**Comment by sweirich** [comment]
Thanks! I've just uploaded the new versions to hackage.
