### ISSUE TITLE
template-haskell dependency 

### ISSUE THREAD

**Issue by ibrahimsag** [sweirich/replib#48]
I get the following error building with ghc 8.8. Any chance we can resolve these?

Great library, Gratitude!

```
[__1] trying: unbound-0.5.1.1 (..)
[__2] trying: RepLib-0.5.4.1 (dependency of unbound)
[__3] next goal: template-haskell (dependency of RepLib)
[__3] rejecting: template-haskell-2.15.0.0/installed-2.15.0.0 (conflict:
RepLib => template-haskell>=2.4 && <2.15)
[__3] skipping: template-haskell-2.15.0.0 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=2.4 && <2.15'
from 'RepLib')
[__3] rejecting: template-haskell-2.14.0.0, template-haskell-2.13.0.0,
```

**Comment by sweirich** [comment]
Template Haskell often makes breaking changes, so upgrading to a new version will take some time.  (It reflects internal data structures of GHC, and these change frequently.) Sorry!  I will leave this issue open, in case I get some free time to look into it more closely.

**Comment by ddssff** [comment]
@ibrahimsag sometimes you just need to change the dependency range in replib.cabal.

**Comment by sweirich** [comment]
Changing the dependency will work. (I downgraded my GHC to 8.8 and have just verified this morning. Will commit and push soon.)

**Comment by sweirich** [comment]
I have just pushed a version that works for ghc 8.8. (Still fails for 8.10).
